apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-state-metrics.fullname" . }}
  labels:
    {{- include "resource-state-metrics.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.telemetryPort }}
      targetPort: telemetry
      protocol: TCP
      name: telemetry
    - port: {{ .Values.service.resourcePort }}
      targetPort: resource
      protocol: TCP
      name: resource
  selector:
    {{- include "resource-state-metrics.selectorLabels" . | nindent 4 }}
